'use strict';

/**
 * @ngdoc function
 * @name minaApp.controller:MainCtrl
 * @description
 * # MainCtrl
 * Controller of the minaApp
 */
angular.module('minaApp')
  .controller('MainCtrl', function ($scope, Instructor) {
    $scope.currentUser = {
      "ID": 3,
      "UID": "preethi-kasireddy",
      "FirstName": "Preethi ",
      "LastName": "Kasireddy",
      "Intro": "A passionate software engineer that loves teaching others everything I learn. In my previous life, I was a venture capitalist at Andreessen Horowitz, where I fell in love with passionate engineers & entrepreneurs and realized I wanted to be \"one of them\" :)",
      "ShortIntro": "Creator of CycleJS and Rx Marbles. Reactive Programming Expert and RxJS Contributor.",
      "GooglePlus": "https://plus.GooglePlus.com/+CraigMcKeachie?rel=author",
      "Twitter": "https://twitter.com/iam_preethi",
      "Facebook": "https://www.facebook.com/rachit.aherwar",
      "GitHub": null,
      "Blog": "https://medium.com/@preethikasireddy",
      "Email": "Kasireddy@gmail.com",
      "Password": "12345678@",
      "Phone": "0968437646",
      "Address": "7105 Plover Circle\nFort Worth\nTexas",
      "SmAvatar": "https://d2eip9sf3oo6c2.cloudfront.net/instructors/avatars/000/000/042/bio/11895272_10154078186552506_3411075844880369856_o.jpg?1451517982",
      "MdAvatar": "https://d2eip9sf3oo6c2.cloudfront.net/instructors/avatars/000/000/042/bio/11895272_10154078186552506_3411075844880369856_o.jpg?1451517982",
      "LgAvatar": "https://d2eip9sf3oo6c2.cloudfront.net/instructors/avatars/000/000/042/bio/11895272_10154078186552506_3411075844880369856_o.jpg?1451517982",
      "TotalCourses": 10,
      "Courses": [
        {
          "ID": 27,
          "TechnologyID": 1,
          "InstructorID": 3,
          "Name": "Start Using React to Build Web Applications",
          "Intro": "React is a \"javascript library for building user interfaces\" from the fine folks at Facebook & Instagram. It strictly focuses on the \"V\" in your MVC applications, and touts a blazing fast virtual DOM diff implementation.\nThis series will explore the basic fundamentals of React to get you started.\nWhen you've finished with this series, be sure to check out React Flux Architecture for real-world React application development.",
          "SmImage": "https://d2eip9sf3oo6c2.cloudfront.net/tech/defaults/course_image_thumb_react.png",
          "MdImage": "https://d2eip9sf3oo6c2.cloudfront.net/series/square_covers/000/000/003/thumb/course_image.png?1457454986",
          "LgImage": "https://d2eip9sf3oo6c2.cloudfront.net/series/covers/000/000/003/full/course_banner.png?1457396165",
          "IsPro": false,
          "TotalLessons": 21,
          "EstimatedTime": 3960,
          "LastUpdate": null,
          "Enrollments": null,
          "Lessons": [
            {
              "ID": 32,
              "CourseID": 0,
              "Name": "Use create-react-app to Setup a Simple React App",
              "Intro": "React requires some initial setup before we can get going with the app. In this lesson, we will use create-react-app to do this initial setup for us.",
              "Image": "https://d1xwtr0qwr70yv.cloudfront.net/assets/tech/react-7b90239e805d8b06ca263be745f8ad5f.svg",
              "EstimatedTime": 64,
              "Video": "~/Videos/747a8fc6b9e502bf74a109693067f511eed1dc8b.mp4",
              "Order": 1,
              "IsPro": false,
              "LastUpdate": null,
              "Course": {
                "ID": 27,
                "TechnologyID": 0,
                "InstructorID": 0,
                "Name": "Start Using React to Build Web Applications",
                "Intro": null,
                "SmImage": null,
                "MdImage": null,
                "LgImage": null,
                "IsPro": false,
                "TotalLessons": 0,
                "EstimatedTime": 0,
                "LastUpdate": null,
                "Enrollments": null,
                "Lessons": null,
                "Technology": {
                  "ID": 1,
                  "Name": "React",
                  "Intro": null,
                  "SmImage": null,
                  "MdImage": null,
                  "LgImage": null,
                  "TotalCourses": 0,
                  "TotalLessons": 0,
                  "LastUpdate": null,
                  "Courses": null
                }
              }
            },
            {
              "ID": 39,
              "CourseID": 0,
              "Name": "Write a \"Hello World\" React Component",
              "Intro": "This lessons goes over what it takes to get React to output simple text to the browser such as Hello Eggheads. This lesson will also introduce stateless functional components. React uses JSX which is a \"JavaScript syntax extension that looks similar to XML.\" While this is not required to use with React, it is highly recommended.",
              "Image": "https://d1xwtr0qwr70yv.cloudfront.net/assets/tech/react-7b90239e805d8b06ca263be745f8ad5f.svg",
              "EstimatedTime": 64,
              "Video": "~/Videos/747a8fc6b9e502bf74a109693067f511eed1dc8b.mp4",
              "Order": 2,
              "IsPro": false,
              "LastUpdate": null,
              "Course": {
                "ID": 27,
                "TechnologyID": 0,
                "InstructorID": 0,
                "Name": "Start Using React to Build Web Applications",
                "Intro": null,
                "SmImage": null,
                "MdImage": null,
                "LgImage": null,
                "IsPro": false,
                "TotalLessons": 0,
                "EstimatedTime": 0,
                "LastUpdate": null,
                "Enrollments": null,
                "Lessons": null,
                "Technology": {
                  "ID": 1,
                  "Name": "React",
                  "Intro": null,
                  "SmImage": null,
                  "MdImage": null,
                  "LgImage": null,
                  "TotalCourses": 0,
                  "TotalLessons": 0,
                  "LastUpdate": null,
                  "Courses": null
                }
              }
            },
            {
              "ID": 41,
              "CourseID": 0,
              "Name": "Display Output in React with a Component's render Method",
              "Intro": "The render method is where the magic happens in your React components to display output to the screen. This lesson explains how to structure your JSX in a React component.",
              "Image": "https://d1xwtr0qwr70yv.cloudfront.net/assets/tech/react-7b90239e805d8b06ca263be745f8ad5f.svg",
              "EstimatedTime": 64,
              "Video": "~/Videos/747a8fc6b9e502bf74a109693067f511eed1dc8b.mp4",
              "Order": 3,
              "IsPro": false,
              "LastUpdate": null,
              "Course": {
                "ID": 27,
                "TechnologyID": 0,
                "InstructorID": 0,
                "Name": "Start Using React to Build Web Applications",
                "Intro": null,
                "SmImage": null,
                "MdImage": null,
                "LgImage": null,
                "IsPro": false,
                "TotalLessons": 0,
                "EstimatedTime": 0,
                "LastUpdate": null,
                "Enrollments": null,
                "Lessons": null,
                "Technology": {
                  "ID": 1,
                  "Name": "React",
                  "Intro": null,
                  "SmImage": null,
                  "MdImage": null,
                  "LgImage": null,
                  "TotalCourses": 0,
                  "TotalLessons": 0,
                  "LastUpdate": null,
                  "Courses": null
                }
              }
            },
            {
              "ID": 42,
              "CourseID": 0,
              "Name": "Set Properties on React Components",
              "Intro": "This lesson will teach you the basics of setting properties (props) in your React components. As stated in Thinking in React, props are how we pass data around in React. We will take a look at what propTypes and defaultProps do for us in React.",
              "Image": "https://d1xwtr0qwr70yv.cloudfront.net/assets/tech/react-7b90239e805d8b06ca263be745f8ad5f.svg",
              "EstimatedTime": 64,
              "Video": "~/Videos/747a8fc6b9e502bf74a109693067f511eed1dc8b.mp4",
              "Order": 4,
              "IsPro": false,
              "LastUpdate": null,
              "Course": {
                "ID": 27,
                "TechnologyID": 0,
                "InstructorID": 0,
                "Name": "Start Using React to Build Web Applications",
                "Intro": null,
                "SmImage": null,
                "MdImage": null,
                "LgImage": null,
                "IsPro": false,
                "TotalLessons": 0,
                "EstimatedTime": 0,
                "LastUpdate": null,
                "Enrollments": null,
                "Lessons": null,
                "Technology": {
                  "ID": 1,
                  "Name": "React",
                  "Intro": null,
                  "SmImage": null,
                  "MdImage": null,
                  "LgImage": null,
                  "TotalCourses": 0,
                  "TotalLessons": 0,
                  "LastUpdate": null,
                  "Courses": null
                }
              }
            },
            {
              "ID": 43,
              "CourseID": 0,
              "Name": "Manage React Component State with setState",
              "Intro": "State is used for properties on a component that will change, versus static properties that are passed in. This lesson introduces you to updating state through a simple text input and displaying that in the browser.",
              "Image": "https://d1xwtr0qwr70yv.cloudfront.net/assets/tech/react-7b90239e805d8b06ca263be745f8ad5f.svg",
              "EstimatedTime": 64,
              "Video": "~/Videos/747a8fc6b9e502bf74a109693067f511eed1dc8b.mp4",
              "Order": 5,
              "IsPro": false,
              "LastUpdate": null,
              "Course": {
                "ID": 27,
                "TechnologyID": 0,
                "InstructorID": 0,
                "Name": "Start Using React to Build Web Applications",
                "Intro": null,
                "SmImage": null,
                "MdImage": null,
                "LgImage": null,
                "IsPro": false,
                "TotalLessons": 0,
                "EstimatedTime": 0,
                "LastUpdate": null,
                "Enrollments": null,
                "Lessons": null,
                "Technology": {
                  "ID": 1,
                  "Name": "React",
                  "Intro": null,
                  "SmImage": null,
                  "MdImage": null,
                  "LgImage": null,
                  "TotalCourses": 0,
                  "TotalLessons": 0,
                  "LastUpdate": null,
                  "Courses": null
                }
              }
            },
            {
              "ID": 44,
              "CourseID": 0,
              "Name": "Use React Components as Children for Other Components",
              "Intro": "The owner-ownee relationship is used to designate a parent-child relationship with React components as it differs from the DOM relationship. This lesson demonstrates how composable React can be when using stateless functions to display data.",
              "Image": "https://d1xwtr0qwr70yv.cloudfront.net/assets/tech/react-7b90239e805d8b06ca263be745f8ad5f.svg",
              "EstimatedTime": 64,
              "Video": "~/Videos/747a8fc6b9e502bf74a109693067f511eed1dc8b.mp4",
              "Order": 6,
              "IsPro": false,
              "LastUpdate": null,
              "Course": {
                "ID": 27,
                "TechnologyID": 0,
                "InstructorID": 0,
                "Name": "Start Using React to Build Web Applications",
                "Intro": null,
                "SmImage": null,
                "MdImage": null,
                "LgImage": null,
                "IsPro": false,
                "TotalLessons": 0,
                "EstimatedTime": 0,
                "LastUpdate": null,
                "Enrollments": null,
                "Lessons": null,
                "Technology": {
                  "ID": 1,
                  "Name": "React",
                  "Intro": null,
                  "SmImage": null,
                  "MdImage": null,
                  "LgImage": null,
                  "TotalCourses": 0,
                  "TotalLessons": 0,
                  "LastUpdate": null,
                  "Courses": null
                }
              }
            },
            {
              "ID": 45,
              "CourseID": 0,
              "Name": "Access Nested Data with Reacts props.children",
              "Intro": "When you're building your React components, you'll probably want to access child properties of the markup. this.props.children accesses the innerHTML or nested components of another component.",
              "Image": "https://d1xwtr0qwr70yv.cloudfront.net/assets/tech/react-7b90239e805d8b06ca263be745f8ad5f.svg",
              "EstimatedTime": 64,
              "Video": "~/Videos/747a8fc6b9e502bf74a109693067f511eed1dc8b.mp4",
              "Order": 7,
              "IsPro": false,
              "LastUpdate": null,
              "Course": {
                "ID": 27,
                "TechnologyID": 0,
                "InstructorID": 0,
                "Name": "Start Using React to Build Web Applications",
                "Intro": null,
                "SmImage": null,
                "MdImage": null,
                "LgImage": null,
                "IsPro": false,
                "TotalLessons": 0,
                "EstimatedTime": 0,
                "LastUpdate": null,
                "Enrollments": null,
                "Lessons": null,
                "Technology": {
                  "ID": 1,
                  "Name": "React",
                  "Intro": null,
                  "SmImage": null,
                  "MdImage": null,
                  "LgImage": null,
                  "TotalCourses": 0,
                  "TotalLessons": 0,
                  "LastUpdate": null,
                  "Courses": null
                }
              }
            },
            {
              "ID": 46,
              "CourseID": 0,
              "Name": "Add Custom propType Validation to React Components",
              "Intro": "In addition to the types built into React.propTypes we can also define our own custom propType validator",
              "Image": "https://d1xwtr0qwr70yv.cloudfront.net/assets/tech/react-7b90239e805d8b06ca263be745f8ad5f.svg",
              "EstimatedTime": 64,
              "Video": "~/Videos/747a8fc6b9e502bf74a109693067f511eed1dc8b.mp4",
              "Order": 8,
              "IsPro": false,
              "LastUpdate": null,
              "Course": {
                "ID": 27,
                "TechnologyID": 0,
                "InstructorID": 0,
                "Name": "Start Using React to Build Web Applications",
                "Intro": null,
                "SmImage": null,
                "MdImage": null,
                "LgImage": null,
                "IsPro": false,
                "TotalLessons": 0,
                "EstimatedTime": 0,
                "LastUpdate": null,
                "Enrollments": null,
                "Lessons": null,
                "Technology": {
                  "ID": 1,
                  "Name": "React",
                  "Intro": null,
                  "SmImage": null,
                  "MdImage": null,
                  "LgImage": null,
                  "TotalCourses": 0,
                  "TotalLessons": 0,
                  "LastUpdate": null,
                  "Courses": null
                }
              }
            },
            {
              "ID": 47,
              "CourseID": 0,
              "Name": "Normalize Events with Reacts Synthetic Event System",
              "Intro": "Event handlers are passed an instance of SyntheticEvent in React. In this video we'll take a look at the wide range of events available to us, including Touch events.",
              "Image": "https://d1xwtr0qwr70yv.cloudfront.net/assets/tech/react-7b90239e805d8b06ca263be745f8ad5f.svg",
              "EstimatedTime": 64,
              "Video": "~/Videos/747a8fc6b9e502bf74a109693067f511eed1dc8b.mp4",
              "Order": 9,
              "IsPro": false,
              "LastUpdate": null,
              "Course": {
                "ID": 27,
                "TechnologyID": 0,
                "InstructorID": 0,
                "Name": "Start Using React to Build Web Applications",
                "Intro": null,
                "SmImage": null,
                "MdImage": null,
                "LgImage": null,
                "IsPro": false,
                "TotalLessons": 0,
                "EstimatedTime": 0,
                "LastUpdate": null,
                "Enrollments": null,
                "Lessons": null,
                "Technology": {
                  "ID": 1,
                  "Name": "React",
                  "Intro": null,
                  "SmImage": null,
                  "MdImage": null,
                  "LgImage": null,
                  "TotalCourses": 0,
                  "TotalLessons": 0,
                  "LastUpdate": null,
                  "Courses": null
                }
              }
            },
            {
              "ID": 48,
              "CourseID": 0,
              "Name": "Use React ref to Get a Reference to Specific Components",
              "Intro": "When you are using React components you need to be able to access specific references to individual component instances. This is done by defining a ref. This lesson will introduce us to some of the nuances when using ref.",
              "Image": "https://d1xwtr0qwr70yv.cloudfront.net/assets/tech/react-7b90239e805d8b06ca263be745f8ad5f.svg",
              "EstimatedTime": 64,
              "Video": "~/Videos/747a8fc6b9e502bf74a109693067f511eed1dc8b.mp4",
              "Order": 10,
              "IsPro": false,
              "LastUpdate": null,
              "Course": {
                "ID": 27,
                "TechnologyID": 0,
                "InstructorID": 0,
                "Name": "Start Using React to Build Web Applications",
                "Intro": null,
                "SmImage": null,
                "MdImage": null,
                "LgImage": null,
                "IsPro": false,
                "TotalLessons": 0,
                "EstimatedTime": 0,
                "LastUpdate": null,
                "Enrollments": null,
                "Lessons": null,
                "Technology": {
                  "ID": 1,
                  "Name": "React",
                  "Intro": null,
                  "SmImage": null,
                  "MdImage": null,
                  "LgImage": null,
                  "TotalCourses": 0,
                  "TotalLessons": 0,
                  "LastUpdate": null,
                  "Courses": null
                }
              }
            }
          ],
          "Technology": {
            "ID": 1,
            "Name": "React",
            "Intro": null,
            "SmImage": null,
            "MdImage": "https://d1xwtr0qwr70yv.cloudfront.net/assets/tech/react-7b90239e805d8b06ca263be745f8ad5f.svg",
            "LgImage": null,
            "TotalCourses": 0,
            "TotalLessons": 0,
            "LastUpdate": null,
            "Courses": null
          }
        },
        {
          "ID": 30,
          "TechnologyID": 1,
          "InstructorID": 3,
          "Name": "Build Your First Production Quality React App",
          "Intro": "With the variety of choice we have in building modern web applications using JavaScript, it can make it difficult to understand where to even begin. We live in a wondrous era, where every problem we have seems to have a corresponding javascript module on npm that we can install with just a few keystrokes. It’s easy!  Often, “easy” can mean the opposite of simple. Easy is “quick to do”, where simple is “quick to understand”.\nKISS.\nIn this course you will learn how to build production quality React applications. We will strive to keep things as simple as possible, with minimal dependencies. Instead of typing npm install, we will build our own simple solutions first, to get a solid understanding of the problems that we are solving through libraries. We will build our tools in a functional style, and write appropriate unit tests to verify that they work as expected.\nIf you are brand new to React, you’ll want to read the documentation and watch our free React Fundamentals course.",
          "SmImage": "https://d2eip9sf3oo6c2.cloudfront.net/tech/defaults/course_image_thumb_react.png",
          "MdImage": "https://d2eip9sf3oo6c2.cloudfront.net/series/square_covers/000/000/092/thumb/EGH_ProductReact-2.png?1485298529",
          "LgImage": "https://d2eip9sf3oo6c2.cloudfront.net/series/covers/000/000/092/full/EGH_ProductReact-2-cover.png?1485298529",
          "IsPro": false,
          "TotalLessons": 24,
          "EstimatedTime": 6660,
          "LastUpdate": null,
          "Enrollments": null,
          "Lessons": [],
          "Technology": {
            "ID": 1,
            "Name": "React",
            "Intro": null,
            "SmImage": null,
            "MdImage": "https://d1xwtr0qwr70yv.cloudfront.net/assets/tech/react-7b90239e805d8b06ca263be745f8ad5f.svg",
            "LgImage": null,
            "TotalCourses": 0,
            "TotalLessons": 0,
            "LastUpdate": null,
            "Courses": null
          }
        },
        {
          "ID": 32,
          "TechnologyID": 1,
          "InstructorID": 3,
          "Name": "Building React Applications with Idiomatic Redux",
          "Intro": "This course will pick up where we left off with the Redux Fundamentals course. If you haven't watched that yet, you are highly encouraged to do so!\nYou are about to learn practical production ready techniques for building your React and Redux applications. You will explore advanced state management, middleware, React Router integration, and other common problems you are likely to encounter while building applications for your clients and customers.\nEven if you have already spent time studying Redux, this course will show you better practices straight from the library's creator Dan Abramov.",
          "SmImage": "https://d2eip9sf3oo6c2.cloudfront.net/tech/defaults/course_image_thumb_react.png",
          "MdImage": "https://d2eip9sf3oo6c2.cloudfront.net/series/square_covers/000/000/053/thumb/redux-solutions-react-sq.png?1464725666",
          "LgImage": "https://d2eip9sf3oo6c2.cloudfront.net/series/covers/000/000/053/full/redux-solutions-cover.png?1464725666",
          "IsPro": false,
          "TotalLessons": 27,
          "EstimatedTime": 8220,
          "LastUpdate": null,
          "Enrollments": null,
          "Lessons": [],
          "Technology": {
            "ID": 1,
            "Name": "React",
            "Intro": null,
            "SmImage": null,
            "MdImage": "https://d1xwtr0qwr70yv.cloudfront.net/assets/tech/react-7b90239e805d8b06ca263be745f8ad5f.svg",
            "LgImage": null,
            "TotalCourses": 0,
            "TotalLessons": 0,
            "LastUpdate": null,
            "Courses": null
          }
        },
        {
          "ID": 34,
          "TechnologyID": 1,
          "InstructorID": 3,
          "Name": "Build a React Native Todo Application",
          "Intro": "In this course we’ll explore getting started with a basic React Native application on both iOS and Android. We’ll learn about using React Native components, how to build custom components, how to layout an application using Flexbox, and how to style components.\nWe’ll also focus on how to use state to control components, how to persist information across application reloads with AsyncStorage, and how to inline edit in a ListView.\nThe ultimate goal is to gain an understanding of how to get started building simple React Native applications.",
          "SmImage": "https://d2eip9sf3oo6c2.cloudfront.net/tech/defaults/course_image_thumb_react.png",
          "MdImage": "https://d2eip9sf3oo6c2.cloudfront.net/series/square_covers/000/000/090/thumb/EGH_ReactNative_ToDo-Final.png?1486518728",
          "LgImage": "https://d2eip9sf3oo6c2.cloudfront.net/series/covers/000/000/090/full/EGH_ReactNative_ToDo-Final-cover.png?1484078267",
          "IsPro": false,
          "TotalLessons": 13,
          "EstimatedTime": 2460,
          "LastUpdate": null,
          "Enrollments": null,
          "Lessons": [],
          "Technology": {
            "ID": 1,
            "Name": "React",
            "Intro": null,
            "SmImage": null,
            "MdImage": "https://d1xwtr0qwr70yv.cloudfront.net/assets/tech/react-7b90239e805d8b06ca263be745f8ad5f.svg",
            "LgImage": null,
            "TotalCourses": 0,
            "TotalLessons": 0,
            "LastUpdate": null,
            "Courses": null
          }
        }
      ],
      "Teachings": [
        "React"
      ]
    }
  });
